env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  no-unused-vars:
    - warn
  indent:
    - warn
    - 4
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - double
  semi:
    - warn
    - always
